---
- name: Create temporary directory
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost
  become: no
  run_once: true

- name: Generate public key
  command:
    ssh-keygen -t rsa -f {{ r_tempfile.path | quote }}/id_rsa  -C "" -N ""
  delegate_to: localhost
  become: no
  run_once: true

- name: Read public key 
  set_fact: 
    temp_public_key: "{{ lookup('file', r_tempfile.path + '/id_rsa.pub') }} "
  delegate_to: localhost
  run_once: true
- name: Read private key 
  set_fact: 
    temp_public_key: "{{ lookup('file', r_tempfile.path + '/id_rsa') }} "
  delegate_to: localhost
  run_once: true

- name: Sign public key
  uri:
    url: "{{ hc_vault_server }}/v1/ssh-client-signer/sign/my-role"
    validate_certs: no
    method: POST
    headers:
      X-Vault-Token: "{{ hc_vault_token }}"
    body: "{{ lookup('template', 'templates/hc_vault_pubkey.j2') }}"
    body_format: json
    return_content: yes
  register: r_sign
  become: no
  delegate_to: localhost
  run_once: true

- debug:
    var: r_sign.json

- name: Store key temporarily
  copy:  
    content: "{{ r_sign.json.data.signed_key }}" 
    dest: "{{ r_tempfile.path }}/signed"
  delegate_to: localhost
  become: no
  run_once: true

# Reconfigure ansible connection values 

- set_fact:
    ansible_ssh_private_key_file: "{{ r_tempfile.path }}/id_rsa"

- set_fact:
    ansible_ssh_extra_args: "-i {{ r_tempfile.path }}/signed"

- set_fact:
    ansible_user: ansible

